name: C/C++ CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Built
      run: make all

    - name: Upload built files
      uses: actions/upload-artifact@v3
      with:
        name: sdcard
        path: ./
