name: Build sys-botbase

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    
    - name: Built
      run: make all

    - name: Upload built files
      uses: actions/upload-artifact@v4
      with:
        name: sdcard
        path: ./sys-botbase/sys-botbase.*
