name: Build sys-botbase

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    # Get current date for release naming
    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%y.%m.%d')" >> $ENV:GITHUB_OUTPUT
    
    - name: Built
      run: |
        sed -i "s/insert_version_here/${{ steps.date.outputs.DATE }}.${{ github.run_number }}/g" sys-botbase/source/main.c
        make all

    - name: Upload built files
      uses: actions/upload-artifact@v4
      with:
        name: sdcard
        path: ./
