name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    
    - name: Built
      run: |
        sed -i "s/insert_date_here/$(date +%s)/g" sys-botbase/source/commands.c
        make all

    - name: Upload built files
      uses: actions/upload-artifact@v4
      with:
        name: sdcard
        path: ./
